### PR TITLE
Add export xlsx button

### LINKED ISSUE #388: [For Treasurer only] Export duty timetable to Excel sheets
As a Treasurer, I would love to have a feature to export the duty timetable to Excel (separate sheets for YIH and AS8), so that my life will be easier.

### PR DESCRIPTION
**Pull request by NicholasCF**
Close #388 

Currently I made it so it just downloads a sheet for the last month e.g. if you click it in November, it gives the excel for October.

I also limited this to admins.

I have checked on random days and the sheet looks correct on those days.

Please check whether this is good.

### CODE REVIEW

**Comment by chrisjwelly** [comment]
> Looks good to me! Just a minor detail tho, I don't have admin privileges HAHA

If Hilda say can then that means can xD 

Okay jk I will try to merge this asap but need to find out what this vulnerability thing D:

**Comment by Hilda-Ang** [comment]
> Okay jk I will try to merge this asap but need to find out what this vulnerability thing D:

🤣 I'm guessing it's cause of `axlsx`?

image

**Comment by NicholasCF** [comment]
> Looks good to me! Just a minor detail tho, I don't have admin privileges HAHA

Eh, I thought ops and logs have admin rights?

**Comment by NicholasCF** [comment]
Since ops and logs don't have admin privileges, do I just make this button available for everyone?

**Comment by Hilda-Ang** [comment]
> Since ops and logs don't have admin privileges, do I just make this button available for everyone?

I've gotten admin privileges, can merge now, thanks!

**Pull request merged**
